### ISSUE TITLE
TypeScript Types

### ISSUE THREAD

**Issue by Silic0nS0ldier** [gulpjs/gulplog#11]
Currently there aren't TypeScript definitions anywhere for `gulplog`. I'm happy to get a PR for this together. If its preferred that this be kept out of the repo it can always be provided via DefinitelyTyped.

**Comment by T99** [comment]
@Silic0nS0ldier Just checking in to see whether or not you made any progress on this before I start writing types myself :smile:

**Comment by Silic0nS0ldier** [comment]
@T99 See the referenced PR.

**Comment by phated** [comment]
Closed by #12 - It'll be available in the next release
