### ISSUE TITLE
TS types missing from published v2.0.0 artifact

### ISSUE THREAD

**Issue by Silic0nS0ldier** [gulpjs/gulplog#15]
### What were you expecting to happen?

TS types (via `index.d.ts`) available to package consumers.

### What actually happened?

Despite inclusion in v2 release notes and `types` attribute being present in `package.json`, the `index.d.ts` file is missing from the published version.

### Please give us a sample of your gulpfile

NA

### Terminal output / screenshots

NA

### Please provide the following information:

NA

### Additional information

To rule out package manager bugs I downloaded the tarball directly (`https://registry.npmjs.org/gulplog/-/gulplog-2.0.0.tgz`) and inspected it. The `index.d.ts` file was missing here as well.

**Comment by phated** [comment]
👍 Looks like it was lost (never added?) from our `files` array

**Comment by Silic0nS0ldier** [comment]
Would seem so, I always forget about that field.
