### ISSUE TITLE
Don't use gulplog v2 until gulp 5 is released

### ISSUE THREAD

**Issue by sgapps-de** [gulpjs/gulplog#17]
Before you open this issue, please complete the following tasks:

* [X ] if you think there is a bug in our code, open this issue.

### What were you expecting to happen?
logger.info should output something

### What actually happened?
nothing

### Please give us a sample of your gulpfile
var logger = require(‘gulplog');

logger.info('Hello worlc!');

### Terminal output / screenshots
<Nothing>

### Please provide the following information:
* Windows / node 18.x
But does not matter

### Additional information
The problem arises because 'gulplog' 2.0.1 uses 'glogg@2.x' which in turn uses 'sparkles@2.x' - and this version ist not compatible with 'sparkles@1.x' which is (indirectly) used by 'gulplog@1.x' which is  used by the current version of 'gulp-cli' (2.3.0). Therefore logging does not work for any new gulpfile or gulp plugin that uses 'npm install gulplog' which will install version 2.0.1 of 'gulplog'. I think 'gulplog' must be changed to use version 1.x of 'glogg' / 'sparkles'. Using the current version of 'gulplog' in 'gulp-cli' will fix the problem for new gulpfiles / plugins but will break all existing!

This is not a problem of a global or local installation of 'gulp' as is written in various places!

**Comment by phated** [comment]
Don't upgrade to breaking versions of gulp libraries until gulp 5 releases. There's no way around this.

**Comment by phated** [comment]
[gulp-cli v3.0.0](https://github.com/gulpjs/gulp-cli/releases/tag/v3.0.0) (which will be included in gulp 5) has been released which listens for gulplog v1 and gulplog v2 messages, so this can be closed. It's still recommended to use gulplog v1 until gulp 5 is released so more people get the updated gulp-cli.
