### ISSUE TITLE
I'm confused

### ISSUE THREAD

**Issue by oliversalzburg** [gulpjs/gulplog#9]
So, gulplog doesn't actually log. Is that intended? If so, how are you supposed to use it?

**Comment by phated** [comment]
It emits on a global event emitter and then some other part of the software can listen to those events and do the actual logging.  We do this for you in gulp-cli.

**Comment by oliversalzburg** [comment]
I'm still confused :( I thought this module can be used as a replacement for `gulp-util` for logging.

But when I `require` it, suddenly no logging at all happens. So I have to register my own handlers and take over _all_ actual printing of the messages. But when I do _that_ everything is suddenly logged twice.

Here is a small test I was running:

``` shell
$ gulp
[09:48:09] Hi!
Hi!
[09:48:09] Using gulpfile C:\Users\OLIVER~1\AppData\Local\Temp\gulplog-test\gulpfile.js
Using gulpfile C:\Users\OLIVER~1\AppData\Local\Temp\gulplog-test\gulpfile.js
[09:48:09] Task 'default' is not in your gulpfile
[09:48:09] Please check the documentation for proper gulpfile formatting

$ cat gulpfile.js
'use strict';
const gulplog = require('gulplog');
gulplog.on('info', console.log.bind(console));
gulplog.info('Hi!');
```

The behavior also differs depending on how gulp is invoked. In the above example, I'm using the global gulp-cli to invoke gulp. This is when I see lines being logged twice. When I don't register my event handler, I only get the usual gulp logging through `fancy-log`. This would actually be my desired outcome, but, to my understanding, not how things should work.

Now, when I invoke gulp directly from my `node_modules`, the behavior changes:

``` shell
$ ./node_modules/gulp/bin/gulp.js
Hi!
Using gulpfile C:\Users\OLIVER~1\AppData\Local\Temp\gulplog-test\gulpfile.js
Task 'default' is not in your gulpfile
Please check the documentation for proper gulpfile formatting
```

**Comment by phated** [comment]
No. It's only a replacement when you are using gulp-cli, which is the recommended CLI to be using now.
